---
Name: wordpressimport
After:
  - 'framework/*'
  - 'cms/*'
---
Director:
  rules:
    'WpImporter_Controller//$Action/$ID/$OtherID': 'WpImporter_Controller'
    'import//$Action': 'WordpressParser'
File:
  allowed_extensions:
    - xml
---
Only:
  moduleexists: 'blog'
---
Blog:
  extensions:
    - 'WordpressImportBlogExtension'

BlogPost:
  extensions:
    - 'WpImportedObject'


---
Only:
  moduleexists: 'comments'
---
Comment:
  extensions:
    - 'WpImportedObject'

WordpressParser:
  extensions:
    - 'WordpressCommentImport'
